# Generated by Django 4.2.6 on 2023-11-04 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_password'),
        ('users', '0004_alter_customuser_password_alter_customuser_phone'),
    ]

    operations = [
    ]
