# Generated by Django 4.2.6 on 2023-11-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_phone'),
        ('users', '0006_customuser_image'),
    ]

    operations = [
    ]
