# Generated by Django 4.2.6 on 2023-11-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20231105_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
