# Generated by Django 4.2.6 on 2024-01-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(choices=[('choice', 'Manzilni tanlash'), ('toshkent', 'Toshkent Shahri'), ('andijon', 'Andijon Viloyati'), ('buxoro', 'Buxoro Viloyati'), ('fargona', "Farg'ona Viloyati"), ('jizzax', 'Jizzax Viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi"), ('namangan', 'Namangan Viloyati'), ('navoiy', 'Navoiy Viloyati'), ('samarqand', 'Samarqand Viloyati'), ('surxondaryo', 'Surxondaryo Viloyati'), ('toshkent_viloyati', 'Toshkent Viloyati'), ('xorazm', 'Xorazm Viloyati')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
