# Generated by Django 4.2.6 on 2023-11-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_status_alter_order_customer_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.IntegerField(),
        ),
    ]
