# Generated by Django 4.2.6 on 2024-01-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=30),
        ),
    ]
