# Generated by Django 4.2.6 on 2023-11-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('ayollar', 'Ayollar'), ('erkaklar', 'Erkaklar'), ('bolalar', 'Bolalar'), ('uy-xojalik', "Uy-Xo'jalik"), ('salomatlik', 'Salomatlik')], default='none', max_length=20),
        ),
    ]
